services:
  db:
    container_name: finance_trading_db
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: trading
